########################################################################
# Parameters to set once the taxon is known
########################################################################

gram: neg # or plus
genus: Pantoea
species: agglomerans

#busco_lineage:  # use --auto-lineage-prok
#busco_lineage: FIXME # consult busco --list-datasets
busco_lineage: enterobacterales

########################################################################
# PGAP parameters
########################################################################

pgap_dir: ~/scratch/pgap

