echo 1>&2 fixme
exit 1

GRAM=neg
GENUS=FIXME
SPECIES=FIXME
STRAIN=FIXME

GENOME_SIZE=5000000

NANOPORE_FQ_GZ=../000NOTES/2020-*-FIXME-demux/output/barcodeFIXME.fastq.gz

ILLUMINA_DIR=../000NOTES/2020-09-10-more-illumina-brc-downloads/
R1_FQ_GZ=$ILLUMINA_DIR/*Pag_FIXME_*_R1.fastq.gz
R2_FQ_GZ=$ILLUMINA_DIR/*Pag_FIXME_*_R2.fastq.gz

USE_FLYE=1
USE_MINIPOLISH=1
USE_RAVEN=1
#USE_REDBEAN=1
#USE_NECAT=1

SAMPLE_DEPTH=50
ASMS_PER_PKG=5
