########################################################################
# Parameters to set once the taxon is known
########################################################################

genus: Pantoea
species: agglomerans

########################################################################
# PGAP parameters
########################################################################

pgap_dir: ~/scratch/pgap

########################################################################
# BAKTA parameters
########################################################################

bakta_db: ~/scratch/bakta/db

########################################################################
# BUSCO parameters
########################################################################

#busco_lineage:  # use --auto-lineage-prok
#busco_lineage: FIXME # consult busco --list-datasets
busco_lineage: enterobacterales

